#!/bin/bash
# DevTeam Session Start Hook
# Loads previous session context and auto-detects project configuration

set -euo pipefail

# Configuration
MEMORY_DIR=".devteam/memory"
DEVTEAM_DIR=".devteam"
CONFIG_FILE=".devteam/config.yaml"

# Source common library for SQLite helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "$SCRIPT_DIR/lib/hook-common.sh" ]]; then
    source "$SCRIPT_DIR/lib/hook-common.sh"
elif [[ -f "$SCRIPT_DIR/../lib/hook-common.sh" ]]; then
    source "$SCRIPT_DIR/../lib/hook-common.sh"
else
    echo "[DevTeam Session Start] Warning: hook-common.sh not found" >&2
    exit 0
fi

# Logging function
log() {
    echo "[DevTeam Session Start] $1"
}

# Output to stdout (will be injected into Claude's context)
output() {
    echo "$1"
}

# ============================================
# SYNC AUTONOMOUS-MODE CONFIG FROM config.yaml
# ============================================
# PHASE 0 (2026-08-26): CONFIG_FILE used to be declared and never read again
# anywhere in this script (docs/reviews/ARCHITECTURE_AUDIT_2026-08-26.md §7)
# -- scripts/state.sh's circuit-breaker/iteration checks always fell through
# to their own hardcoded numbers instead. This parses the `autonomous:`
# block of config.yaml and writes the resolved values to
# .devteam/autonomous-runtime.env, which scripts/state.sh's start_session(),
# should_trip_circuit_breaker(), and is_max_iterations_reached() now read.
# Runs on every session start so editing config.yaml takes effect on the
# next session, without needing a yq/YAML-parser dependency -- a few
# targeted grep/sed lines scoped to the known keys, same lightweight style
# already used elsewhere in this script (see detect_languages/
# detect_package_managers below).
RUNTIME_CONFIG_FILE="${DEVTEAM_DIR}/autonomous-runtime.env"

# Hardcoded fallbacks -- intentionally match .devteam/config.yaml's own
# shipped defaults, so a missing/unreadable config file behaves the same as
# a fresh, un-customized project rather than reverting to an unrelated number.
DEFAULT_AUTONOMOUS_ENABLED="true"
DEFAULT_MAX_ITERATIONS="50"
DEFAULT_MAX_CONSECUTIVE_FAILURES="5"
DEFAULT_COOLDOWN_MINUTES="5"

# Print only the lines belonging to the top-level `autonomous:` section of
# config.yaml (from the `autonomous:` line up to, but not including, the
# next top-level key), or nothing if the file/section isn't found.
_extract_autonomous_block() {
    awk '
        /^autonomous:[[:space:]]*$/ { in_block=1; next }
        in_block && /^[A-Za-z_][A-Za-z0-9_]*:/ { in_block=0 }
        in_block { print }
    ' "$CONFIG_FILE" 2>/dev/null
    return 0
}

sync_autonomous_config() {
    mkdir -p "$DEVTEAM_DIR" 2>/dev/null || true

    local block=""
    local cfg_source="defaults (${CONFIG_FILE} not found)"
    if [[ -f "$CONFIG_FILE" ]]; then
        block=$(_extract_autonomous_block)
        if [[ -n "$block" ]]; then
            cfg_source="$CONFIG_FILE"
        else
            cfg_source="defaults (no autonomous: block in ${CONFIG_FILE})"
        fi
    fi

    local cfg_enabled cfg_max_iter cfg_max_fail cfg_cooldown
    cfg_enabled=$(printf '%s\n' "$block" | grep -m1 -E '^[[:space:]]*enabled:' | sed -E 's/^[[:space:]]*enabled:[[:space:]]*([A-Za-z]+).*/\1/' || echo "")
    cfg_max_iter=$(printf '%s\n' "$block" | grep -m1 -E '^[[:space:]]*max_iterations:' | sed -E 's/^[[:space:]]*max_iterations:[[:space:]]*([0-9]+).*/\1/' || echo "")
    cfg_max_fail=$(printf '%s\n' "$block" | grep -m1 -E '^[[:space:]]*max_consecutive_failures:' | sed -E 's/^[[:space:]]*max_consecutive_failures:[[:space:]]*([0-9]+).*/\1/' || echo "")
    cfg_cooldown=$(printf '%s\n' "$block" | grep -m1 -E '^[[:space:]]*cooldown_minutes:' | sed -E 's/^[[:space:]]*cooldown_minutes:[[:space:]]*([0-9]+).*/\1/' || echo "")

    # Validate each field independently; fall back per-field rather than
    # discarding the whole block if one key is missing/malformed.
    [[ "$cfg_enabled" =~ ^(true|false)$ ]] || cfg_enabled="$DEFAULT_AUTONOMOUS_ENABLED"
    { [[ "$cfg_max_iter" =~ ^[0-9]+$ ]] && [ "$cfg_max_iter" -gt 0 ]; } || cfg_max_iter="$DEFAULT_MAX_ITERATIONS"
    { [[ "$cfg_max_fail" =~ ^[0-9]+$ ]] && [ "$cfg_max_fail" -gt 0 ]; } || cfg_max_fail="$DEFAULT_MAX_CONSECUTIVE_FAILURES"
    [[ "$cfg_cooldown" =~ ^[0-9]+$ ]] || cfg_cooldown="$DEFAULT_COOLDOWN_MINUTES"

    cat > "$RUNTIME_CONFIG_FILE" << EOF
# Auto-generated by hooks/session-start.sh from ${CONFIG_FILE}'s autonomous: block.
# Regenerated at the start of every Claude Code session. Do not edit by hand --
# edit ${CONFIG_FILE}'s autonomous: block instead, then start a new session.
DEVTEAM_AUTONOMOUS_ENABLED=${cfg_enabled}
DEVTEAM_MAX_ITERATIONS=${cfg_max_iter}
DEVTEAM_MAX_CONSECUTIVE_FAILURES=${cfg_max_fail}
DEVTEAM_CIRCUIT_BREAKER_COOLDOWN_MINUTES=${cfg_cooldown}
EOF

    output "## Autonomous Mode Config"
    output ""
    output "- **Source:** $cfg_source"
    output "- **Enabled:** $cfg_enabled"
    output "- **Max Iterations:** $cfg_max_iter"
    output "- **Max Consecutive Failures (circuit breaker):** $cfg_max_fail"
    output "- **Circuit Breaker Cooldown (minutes):** $cfg_cooldown"
    output ""

    log "Synced autonomous config from $cfg_source -> $RUNTIME_CONFIG_FILE"
}

# ============================================
# LOAD PREVIOUS SESSION MEMORY
# ============================================
load_session_memory() {
    if [ -d "$MEMORY_DIR" ]; then
        # Find most recent memory file
        LATEST=$(ls -t "$MEMORY_DIR"/session-*.md 2>/dev/null | head -1)

        if [ -n "$LATEST" ] && [ -f "$LATEST" ]; then
            log "Loading previous session context from $LATEST"
            output ""
            output "## Previous Session Context"
            output ""
            cat "$LATEST"
            output ""
            output "---"
            output ""
        fi
    fi
}

# ============================================
# LOAD CURRENT STATE
# ============================================
load_state_summary() {
    if db_exists 2>/dev/null; then
        log "Loading project state from database"

        # Extract key information from SQLite
        local safe_session_id
        safe_session_id=$(get_current_session 2>/dev/null || echo "")
        safe_session_id="${safe_session_id//\'/\'\'}"
        CURRENT_SPRINT=$(db_query "SELECT sprint_id FROM sessions WHERE id = '$safe_session_id';" 2>/dev/null || echo "none")
        CURRENT_TASK=$(db_query "SELECT current_task_id FROM sessions WHERE id = '$safe_session_id';" 2>/dev/null || echo "none")
        PHASE=$(db_query "SELECT current_phase FROM sessions WHERE id = '$safe_session_id';" 2>/dev/null || echo "unknown")

        CURRENT_SPRINT="${CURRENT_SPRINT:-none}"
        CURRENT_TASK="${CURRENT_TASK:-none}"
        PHASE="${PHASE:-unknown}"

        output "## Current Project State"
        output ""
        output "- **Current Sprint:** $CURRENT_SPRINT"
        output "- **Current Task:** $CURRENT_TASK"
        output "- **Phase:** $PHASE"
        output ""

        # Check for autonomous mode
        if [ -f ".devteam/autonomous-mode" ]; then
            output "- **Mode:** Autonomous (running until complete)"
            output ""
        fi
    fi
}

# ============================================
# AUTO-DETECT PROJECT LANGUAGES
# ============================================
detect_languages() {
    log "Detecting project languages..."

    DETECTED=""

    # Python
    if [ -f "pyproject.toml" ] || [ -f "requirements.txt" ] || [ -f "setup.py" ]; then
        DETECTED="$DETECTED python"
    fi

    # TypeScript/JavaScript
    if [ -f "package.json" ] || [ -f "tsconfig.json" ]; then
        DETECTED="$DETECTED typescript"
    fi

    # Go
    if [ -f "go.mod" ]; then
        DETECTED="$DETECTED go"
    fi

    # Rust
    if [ -f "Cargo.toml" ]; then
        DETECTED="$DETECTED rust"
    fi

    # Java
    if [ -f "pom.xml" ] || [ -f "build.gradle" ]; then
        DETECTED="$DETECTED java"
    fi

    # C#
    if ls *.csproj 1> /dev/null 2>&1 || ls *.sln 1> /dev/null 2>&1; then
        DETECTED="$DETECTED csharp"
    fi

    # Ruby
    if [ -f "Gemfile" ]; then
        DETECTED="$DETECTED ruby"
    fi

    # PHP
    if [ -f "composer.json" ]; then
        DETECTED="$DETECTED php"
    fi

    if [ -n "$DETECTED" ]; then
        output "## Detected Languages"
        output ""
        for lang in $DETECTED; do
            output "- $lang"
        done
        output ""
        output "Consider enabling LSP servers for these languages for better code intelligence."
        output "See \`mcp-configs/lsp-servers.json\` for configuration."
        output ""
    fi
}

# ============================================
# DETECT PACKAGE MANAGERS
# ============================================
detect_package_managers() {
    log "Detecting package managers..."

    # Python
    if [ -f "uv.lock" ]; then
        output "- **Python:** uv (recommended)"
    elif [ -f "poetry.lock" ]; then
        output "- **Python:** poetry"
    elif [ -f "Pipfile.lock" ]; then
        output "- **Python:** pipenv"
    elif [ -f "requirements.txt" ]; then
        output "- **Python:** pip"
    fi

    # Node.js
    if [ -f "pnpm-lock.yaml" ]; then
        output "- **Node.js:** pnpm"
    elif [ -f "yarn.lock" ]; then
        output "- **Node.js:** yarn"
    elif [ -f "bun.lockb" ]; then
        output "- **Node.js:** bun"
    elif [ -f "package-lock.json" ]; then
        output "- **Node.js:** npm"
    fi
}

# ============================================
# MAIN EXECUTION
# ============================================
main() {
    output "# DevTeam Session Initialized"
    output ""

    # Load previous context if available
    load_session_memory

    # Load current state
    load_state_summary

    # Parse config.yaml's autonomous: block into .devteam/autonomous-runtime.env
    # so scripts/state.sh enforces the configured limits, not hardcoded ones.
    sync_autonomous_config

    # Detect project configuration
    detect_languages

    output "## Package Managers"
    output ""
    detect_package_managers
    output ""

    log "Session initialization complete"
}

# Run main function
main
